In [14]:
zmienna = "COS CIEKAWEGO"
numer = 2.7
print(zmienna)
print(zmienna + " " + str(numer))


print(len(zmienna))
print(type(numer))

print(zmienna[9])
print(zmienna[0:4])

print(zmienna[-9:])

COS CIEKAWEGO
COS CIEKAWEGO 2.7
13
<class 'float'>
W
COS 
CIEKAWEGO


In [19]:
tab = ["Dom",56,343,7.9,40] #wywołanie listy
print(tab)
print(type(tab))

tab_2 = [tab,[45,38,2.5],23]
print(tab_2)

tab_2.append("Kot")
print(tab_2)
print(tab_2[0][1])

['Dom', 56, 343, 7.9, 40]
<class 'list'>
[['Dom', 56, 343, 7.9, 40], [45, 38, 2.5], 23]
[['Dom', 56, 343, 7.9, 40], [45, 38, 2.5], 23, 'Kot']
56


In [21]:
krot = tuple()
krot = (34,67,34.6,"DOM")
print(krot)

(34, 67, 34.6, 'DOM')


In [25]:
x = "KOT"
if x == "KOT":
  print("Prawda")
else:
  print("Falsz")
x = "G"
print(x)

Prawda
G


In [29]:
for i in "DOM":
  print(i)
print("\n")
for i in range(0,len(zmienna)):
  print(zmienna[i])

D
O
M


C
O
S
 
C
I
E
K
A
W
E
G
O


In [31]:
def dodaj(x,y,z):
  return x+y+z


def dodaj_2(x,y,z):
  return x+y+z,  x, y, z



In [34]:
print(dodaj(34,6,5.4))
k  = dodaj_2(34,6,5.4)
print(k)

45.4
(45.4, 34, 6, 5.4)


In [37]:
import numpy as np

arr = np.array([46,56,34,67.5], dtype=int)
print(arr)


arr_2D = np.array((arr,[23,56,23,9]))
print(arr_2D)

arr_2D_rand = np.ndarray((4,3))
print(arr_2D_rand)

arr_2D_rand[0][1] = 1
print(arr_2D_rand)

[46 56 34 67]
[[46 56 34 67]
 [23 56 23  9]]
[[1.65466458e-316 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.82116729e-043]
 [5.44621803e-090 9.33114435e+164 2.83073936e-033]
 [1.25758928e-047 3.99910963e+252 1.46030983e-319]]
[[1.65466458e-316 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.82116729e-043]
 [5.44621803e-090 9.33114435e+164 2.83073936e-033]
 [1.25758928e-047 3.99910963e+252 1.46030983e-319]]


In [47]:

cos = np.array([1,2,3,5,6,4,4.5])
cos.fill(0)
print(cos)

[0. 0. 0. 0. 0. 0. 0.]


In [69]:
arr_ones = np.ones((3,4),dtype=int)


arr_zeros = np.zeros((3,4),dtype=int)

In [75]:
arr_zeros[0] = 4
arr_zeros[1] = 1,2,3,4
arr_zeros[:,3] = 15
print(arr_zeros)

[[ 4  4  4 15]
 [ 1  2  3 15]
 [ 0  0 15 15]]


In [79]:
np.sin(arr_zeros)
np.cos(arr_zeros)
arr_zeros.shape

(3, 4)

In [84]:
def wysrodkuj(A):
    for i in A :
      sum = sum + i


In [85]:
print(wysrodkuj(arr_zeros))

UnboundLocalError: ignored